/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buatjframe;

import javax.swing.JOptionPane;

/**
 *
 * @author masdi
 */
public class warung extends javax.swing.JFrame {

    /**
     * Creates new form warung
     */
    public warung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bhitung = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Rbgoreng = new javax.swing.JRadioButton();
        Rbmie = new javax.swing.JRadioButton();
        Rbayam = new javax.swing.JRadioButton();
        rbkambing = new javax.swing.JRadioButton();
        Rbnasi = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txtng = new javax.swing.JTextField();
        Txtmg = new javax.swing.JTextField();
        Txtsa = new javax.swing.JTextField();
        Txtsk = new javax.swing.JTextField();
        Txtns = new javax.swing.JTextField();
        Txtjmlng = new javax.swing.JTextField();
        txtjmlmg = new javax.swing.JTextField();
        txtjmlsa = new javax.swing.JTextField();
        txtjmlsk = new javax.swing.JTextField();
        txtjmlns = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bhitung.setText("Hitung");
        Bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhitungActionPerformed(evt);
            }
        });

        Bhapus.setText("Hapus");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });

        Bkeluar.setText("Keluar");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jLabel2.setText("X");

        jLabel3.setText("X");

        jLabel4.setText("X");

        jLabel5.setText("X");

        Rbgoreng.setText("Nasi Goreng");
        Rbgoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbgorengActionPerformed(evt);
            }
        });

        Rbmie.setText("Mie Goreng");
        Rbmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbmieActionPerformed(evt);
            }
        });

        Rbayam.setText("Soto Ayam");
        Rbayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbayamActionPerformed(evt);
            }
        });

        rbkambing.setText("Sop Kambing");
        rbkambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbkambingActionPerformed(evt);
            }
        });

        Rbnasi.setText("Nasi");
        Rbnasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbnasiActionPerformed(evt);
            }
        });

        jLabel7.setText("Warung Laris terus");

        jLabel8.setText("Jumlah Harga");

        Txtsk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtskActionPerformed(evt);
            }
        });

        txtjmlmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlmgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Txtmg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Rbayam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(Txtsk, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(Txtng, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rbnasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Txtns, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(rbkambing))
                                .addGap(18, 18, 18)
                                .addComponent(txtharga)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtjmlmg, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(Txtjmlng)
                                    .addComponent(txtjmlsk)
                                    .addComponent(txtjmlsa)
                                    .addComponent(txtjmlns)))
                            .addComponent(Bhapus))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rbmie, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rbgoreng, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(Bhitung)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bkeluar)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Rbgoreng)
                    .addComponent(Txtng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txtjmlng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Rbmie)
                        .addComponent(Txtmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtjmlmg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Rbayam)
                    .addComponent(Txtsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmlsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbkambing)
                    .addComponent(Txtsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmlsk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Rbnasi)
                    .addComponent(Txtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjmlns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bhitung)
                    .addComponent(Bhapus))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bkeluar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbgorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbgorengActionPerformed
        // TODO add your handling code here:
        int nasigoreng = 10000;
        if (Rbgoreng.isSelected())
        {
        Txtng.setText(""+Rbgoreng.getText());
        Txtng.setText(""+nasigoreng);
        }
        else
        {
        Txtng.setText("");
        }

        
    }//GEN-LAST:event_RbgorengActionPerformed

    private void TxtskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtskActionPerformed

    private void txtjmlmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlmgActionPerformed

    private void RbmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbmieActionPerformed
        // TODO add your handling code here:
        int miegoreng = 12000;
        if (Rbmie.isSelected())
        {
        Txtmg.setText(""+Rbmie.getText());
        Txtmg.setText(""+miegoreng);
        }
        else
        {
        Txtmg.setText("");
        }

    }//GEN-LAST:event_RbmieActionPerformed

    private void RbayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbayamActionPerformed
        // TODO add your handling code here:
        int sotoayam = 15000;
        if (Rbayam.isSelected())
        {
        Txtsa.setText(""+Rbayam.getText());
        Txtsa.setText(""+sotoayam);
        }
        else
        {
        Txtsa.setText("");
        }

    }//GEN-LAST:event_RbayamActionPerformed

    private void rbkambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbkambingActionPerformed
        // TODO add your handling code here:
        int sopkambing = 22000;
        if (rbkambing.isSelected())
        {
        Txtsk.setText(""+rbkambing.getText());
        Txtsk.setText(""+sopkambing);
        }
        else
        {
        Txtsk.setText("");
        }

    }//GEN-LAST:event_rbkambingActionPerformed

    private void RbnasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbnasiActionPerformed
        // TODO add your handling code here:
        int nasi = 5000;
        if (Rbnasi.isSelected())
        {
        Txtns.setText(""+Rbnasi.getText());
        Txtns.setText(""+nasi);
        }
        else
        {
        Txtns.setText("");
        }
    }//GEN-LAST:event_RbnasiActionPerformed

    private void BhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhitungActionPerformed
        // TODO add your handling code here:
        int total=0;
         if(Rbgoreng.isSelected())
         {
         String ng = Txtjmlng.getText();
         int jmlng = Integer.parseInt(ng);
         int hargang = jmlng*10000;
         total=total+hargang;
         }
         if(Rbmie.isSelected())
         {
         String mg = txtjmlmg.getText();
         int jmlmg = Integer.parseInt(mg);
         int hargamg = jmlmg*12000;
         total=total+hargamg;
         }
         if(Rbayam.isSelected())
         {
         String sa = txtjmlsa.getText();
         int jmlsa = Integer.parseInt(sa);
         int hargasa = jmlsa*15000;
         total=total+hargasa;
         }
         if(rbkambing.isSelected())
         {String sk = txtjmlsk.getText();
         int jmlsk = Integer.parseInt(sk);
         int hargask = jmlsk*22000;
         total=total+hargask;
         }
         if(Rbnasi.isSelected())
         {
         String ns = txtjmlns.getText();
         int jmlns = Integer.parseInt(ns);
         int hargans = jmlns*5000;
         total=total+hargans;
         }
         txtharga.setText(""+total);


    }//GEN-LAST:event_BhitungActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
         Txtng.setText("");
         Txtjmlng.setText("");
         Txtmg.setText("");
         txtjmlmg.setText("");
         Txtsa.setText("");
         txtjmlsa.setText("");
         Txtsk.setText("");
         txtjmlsk.setText("");
         Txtns.setText("");
         txtjmlns.setText("");
         txtharga.setText("");
    }//GEN-LAST:event_BhapusActionPerformed

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "keluar Program","Keluar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
         if(x==JOptionPane.YES_NO_OPTION)
         {
         dispose();
         }
    }//GEN-LAST:event_BkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bhitung;
    private javax.swing.JButton Bkeluar;
    private javax.swing.JRadioButton Rbayam;
    private javax.swing.JRadioButton Rbgoreng;
    private javax.swing.JRadioButton Rbmie;
    private javax.swing.JRadioButton Rbnasi;
    private javax.swing.JTextField Txtjmlng;
    private javax.swing.JTextField Txtmg;
    private javax.swing.JTextField Txtng;
    private javax.swing.JTextField Txtns;
    private javax.swing.JTextField Txtsa;
    private javax.swing.JTextField Txtsk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rbkambing;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjmlmg;
    private javax.swing.JTextField txtjmlns;
    private javax.swing.JTextField txtjmlsa;
    private javax.swing.JTextField txtjmlsk;
    // End of variables declaration//GEN-END:variables
}
